name: flutter_quill2
description: 
version: 0.3.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_quill:
    path: ../flutter-quill
      
  vsc_quill_delta_to_html: ^1.0.3

  path_provider: ^2.1.0
  filesystem_picker: ^3.1.0
  file_picker: ^5.2.2
  measure_size: ^4.0.0
  font_awesome_flutter: ^10.5.0
  font_awesome_flutter_named: ^1.1.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1

dependency_overrides:
  intl: ^0.17.0

# The following section is specific to Flutter packages.
flutter:
