name: flutter_quill2
description: 
version: 0.3.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_quill:
    git:
      url: https://github.com/singerdmx/flutter-quill.git
      
  vsc_quill_delta_to_html: ^1.0.3

  image_picker: ^0.8.5+3
  photo_view: ^0.14.0
  video_player: ^2.4.2
  youtube_player_flutter: ^8.1.1
  gallery_saver: ^2.3.2
  string_validator: ^1.0.0
  universal_html: ^2.2.1
  url_launcher: ^6.1.9
  path_provider: ^2.0.9
  filesystem_picker: ^3.1.0
  file_picker: ^5.2.2
  measure_size: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1

dependency_overrides:
  intl: ^0.17.0

# The following section is specific to Flutter packages.
flutter:
